### ISSUE TITLE
Icons and App-Logo

### ISSUE THREAD

**Issue by Niggo2001** [Jenns-Entertainment/DartsWithFriends#15]
Icons needed:

- [ ] Home
- [ ] Settings
- [ ] Profile
- [ ] Logo
- [ ] Edit (Pencil)

**Comment by Niggo2001** [comment]
Added Icons to Sprint:

- Home
- Settings
- Profile

**Comment by Niggo2001** [comment]
Added Logo-Icon, discuss in Meeting

**Comment by Emil3005** [comment]
Hello,
@Niggo2001 please also add the following icon:

Edit Pencil 

![Image](https://github.com/Jenns-Entertainment/DartsWithFriends/assets/34603464/6f954810-dfc3-472a-98d3-bd1082ee6124)



Take the image as inspiration. Please add this icon to the repository in the colour blue, white and black

**Comment by Emil3005** [comment]
Please also add an arrow, indicating that one statistic is better than the other.

2 in total

first pointing left
second pointig right (just mirror first)
